version: '3'
services:
  go:
    build: .
    # ports:
    #   - "9487:9487"
    networks:
      - app
  redis:
    image: redis
    ports:
      - "6300:6379"
    command: redis-server --appendonly yes
    networks:
      - app
  vue:
    build: ./vue
    ports:
      - "443:443"
    networks:
      - app
networks:
  app:
    driver: bridge